version: "3.7"
services:
    explorer1:
        image: explorer:latest
        build:
            context: ./
        network_mode: host
        command: ["http-server", "/usr/src/app/dist", "-p 8081"]

    explorer2:
        image: explorer:latest
        build:
            context: ./
        network_mode: host
        command: ["http-server", "/usr/src/app/dist", "-p 8082"]
